import { QueryProvider } from "@/core/react-query/QueryProvider";
import "@/core/styles/globals.css";
import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import type { ReactNode } from "react";

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["300", "500", "700"],
});

export default function Layout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="ko" className={notoSansKR.className}>
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
